name: farmer_app
description: Voice-first farming advice app for small & marginal farmers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  
  # Voice & Audio - Updated versions
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  
  # Storage & Data
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  
  # Network & API
  http: ^1.1.0
  connectivity_plus: ^7.0.0
  
  # Media & Camera
  image_picker: ^1.0.7
  image: ^4.0.17
  
  # Location
  geolocator: ^14.0.2
  
  # Utils
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/icons/
  #   - assets/images/
  #   - assets/audio/